# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Playerdata(models.Model):
    id = models.IntegerField(blank=True, null=False,primary_key=True)
    sofifa_id = models.IntegerField(blank=True, null=True)
    short_name = models.TextField(blank=True, null=True)
    long_name = models.TextField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    height_cm = models.IntegerField(blank=True, null=True)
    weight_kg = models.IntegerField(blank=True, null=True)
    nationality = models.TextField(blank=True, null=True)
    club = models.TextField(blank=True, null=True)
    overall = models.IntegerField(blank=True, null=True)
    potential = models.IntegerField(blank=True, null=True)
    value_eur = models.IntegerField(blank=True, null=True)
    wage_eur = models.IntegerField(blank=True, null=True)
    preferred_foot = models.TextField(blank=True, null=True)
    international_reputation = models.IntegerField(blank=True, null=True)
    weak_foot = models.IntegerField(blank=True, null=True)
    skill_moves = models.IntegerField(blank=True, null=True)
    work_rate = models.TextField(blank=True, null=True)
    release_clause_eur = models.FloatField(blank=True, null=True)
    team_position = models.TextField(blank=True, null=True)
    team_jersey_number = models.FloatField(blank=True, null=True)
    joined = models.TextField(blank=True, null=True)
    contract_valid_until = models.FloatField(blank=True, null=True)
    pace = models.IntegerField(blank=True, null=True)
    shooting = models.IntegerField(blank=True, null=True)
    passing = models.IntegerField(blank=True, null=True)
    dribbling = models.IntegerField(blank=True, null=True)
    defending = models.IntegerField(blank=True, null=True)
    physic = models.IntegerField(blank=True, null=True)
    gk_diving = models.IntegerField(blank=True, null=True)
    gk_handling = models.IntegerField(blank=True, null=True)
    gk_kicking = models.IntegerField(blank=True, null=True)
    gk_reflexes = models.IntegerField(blank=True, null=True)
    gk_speed = models.IntegerField(blank=True, null=True)
    gk_positioning = models.IntegerField(blank=True, null=True)
    attacking_crossing = models.IntegerField(blank=True, null=True)
    attacking_finishing = models.IntegerField(blank=True, null=True)
    attacking_heading_accuracy = models.IntegerField(blank=True, null=True)
    attacking_short_passing = models.IntegerField(blank=True, null=True)
    attacking_volleys = models.IntegerField(blank=True, null=True)
    skill_dribbling = models.IntegerField(blank=True, null=True)
    skill_curve = models.IntegerField(blank=True, null=True)
    skill_fk_accuracy = models.IntegerField(blank=True, null=True)
    skill_long_passing = models.IntegerField(blank=True, null=True)
    skill_ball_control = models.IntegerField(blank=True, null=True)
    movement_acceleration = models.IntegerField(blank=True, null=True)
    movement_sprint_speed = models.IntegerField(blank=True, null=True)
    movement_agility = models.IntegerField(blank=True, null=True)
    movement_reactions = models.IntegerField(blank=True, null=True)
    movement_balance = models.IntegerField(blank=True, null=True)
    power_shot_power = models.IntegerField(blank=True, null=True)
    power_jumping = models.IntegerField(blank=True, null=True)
    power_stamina = models.IntegerField(blank=True, null=True)
    power_strength = models.IntegerField(blank=True, null=True)
    power_long_shots = models.IntegerField(blank=True, null=True)
    mentality_aggression = models.IntegerField(blank=True, null=True)
    mentality_interceptions = models.IntegerField(blank=True, null=True)
    mentality_positioning = models.IntegerField(blank=True, null=True)
    mentality_vision = models.IntegerField(blank=True, null=True)
    mentality_penalties = models.IntegerField(blank=True, null=True)
    mentality_composure = models.IntegerField(blank=True, null=True)
    defending_marking = models.IntegerField(blank=True, null=True)
    defending_standing_tackle = models.IntegerField(blank=True, null=True)
    defending_sliding_tackle = models.IntegerField(blank=True, null=True)
    goalkeeping_diving = models.IntegerField(blank=True, null=True)
    goalkeeping_handling = models.IntegerField(blank=True, null=True)
    goalkeeping_kicking = models.IntegerField(blank=True, null=True)
    goalkeeping_positioning = models.IntegerField(blank=True, null=True)
    goalkeeping_reflexes = models.IntegerField(blank=True, null=True)
    ls = models.IntegerField(blank=True, null=True)
    st = models.IntegerField(blank=True, null=True)
    rs = models.IntegerField(blank=True, null=True)
    lw = models.IntegerField(blank=True, null=True)
    lf = models.IntegerField(blank=True, null=True)
    cf = models.IntegerField(blank=True, null=True)
    rf = models.IntegerField(blank=True, null=True)
    rw = models.IntegerField(blank=True, null=True)
    lam = models.IntegerField(blank=True, null=True)
    cam = models.IntegerField(blank=True, null=True)
    ram = models.IntegerField(blank=True, null=True)
    lm = models.IntegerField(blank=True, null=True)
    lcm = models.IntegerField(blank=True, null=True)
    cm = models.IntegerField(blank=True, null=True)
    rcm = models.IntegerField(blank=True, null=True)
    rm = models.IntegerField(blank=True, null=True)
    lwb = models.IntegerField(blank=True, null=True)
    ldm = models.IntegerField(blank=True, null=True)
    cdm = models.IntegerField(blank=True, null=True)
    rdm = models.IntegerField(blank=True, null=True)
    rwb = models.IntegerField(blank=True, null=True)
    lb = models.IntegerField(blank=True, null=True)
    lcb = models.IntegerField(blank=True, null=True)
    cb = models.IntegerField(blank=True, null=True)
    rcb = models.IntegerField(blank=True, null=True)
    rb = models.IntegerField(blank=True, null=True)
    position_1 = models.TextField(db_column='Position_1', blank=True, null=True)  # Field name made lowercase.
    position_2 = models.TextField(db_column='Position_2', blank=True, null=True)  # Field name made lowercase.
    position_3 = models.TextField(db_column='Position_3', blank=True, null=True)  # Field name made lowercase.
    position = models.TextField(db_column='Position', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'catalog_playerdata'
