# Generated by Django 3.0.5 on 2020-04-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200426_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerdata',
            options={'managed': True},
        ),
    ]
