# Generated by Django 3.0.5 on 2020-04-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200426_0857'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Playerdata',
            table=None,
        ),
    ]
