# Generated by Django 3.0.5 on 2020-04-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200426_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Playerdata',
            options={'managed': True},
        ),
    ]
