# Generated by Django 3.0.5 on 2020-04-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200426_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerdata',
            options={'managed': False},
        ),
    ]
