# Generated by Django 3.0.5 on 2020-04-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200426_0940'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playerdata',
            table='catalog_playerdata',
        ),
    ]
